config/routes.rb
Capitan::Application.routes.draw do

  mount OpenSesame::Engine => "/welcome", :as => "opensesame"

  match '/notifications/:id', :to => 'notifications#create', :via => [:get, :post]

  root to: "home#show"

  resources :jobs, :only => [:show, :index] do
    resources :branches
  end

  resources :stacks

end

app/models/stack.rb
class Stack < ActiveRecord::Base
  has_many :jobs

  attr_accessible :job_ids, :name
  accepts_nested_attributes_for :jobs

  def display_name
    name.titleize
  end

  def result
    success? ? :success :
      failure? ? :failure :
        :unknown
  end

  def result_description
    success? ? "Green - Build stack passing, app is deploy ready" :
      failure? ? "Red - Build failing, don't deploy" :
        "Yellow - Build status unknown, don't deploy"
  end

  def success?
    jobs.all? { |job| job.success? } && jobs.map(&:sha).uniq.size == 1
  end

  def failure?
    jobs.any? { |job| job.failure? }
  end

  def unknown_status?
    jobs.any? { |job| job.unknown_status? }
  end
end

app/controllers/stacks_controller.rb
class StacksController < ApplicationController

  respond_to :html, :json

  def index
    @stacks = StackDecorator.decorate(Stack.all)
    respond_with(@stacks)
  end

  def show
    @stack = StackDecorator.new(Stack.find(params[:id]))
    respond_with(@stack)
  end

  def new
    @stack = Stack.new
  end

  def edit
    @stack = Stack.find(params[:id])
  end

  def create
    @stack = Stack.new(params[:stack])
    @stack.save
    set_flash_message(@stack)
    respond_with(@stack)
  end

  def update
    @stack = Stack.find(params[:id])
    @stack.update_attributes(params[:stack])

    @stack.save
    set_flash_message(@stack)
    respond_with(@stack)
  end

  private

  def set_flash_message(stack)
    if stack.errors.any?
      flash[:error] = @stack.errors.full_messages
    else
      flash[:success] = "Your stack has been updated!"
    end
  end
end

app/views/stacks/_form.html.erb
<%= form_for @stack do |f| %>
  <%= f.label :name %><%= f.text_field :name %>

  <h3>Jobs</h3>
  <div>
    <%= f.select :job_ids, Job.all.map { |job| [job.name, job.id]}, 
      { :prompt => "Please select"},
      { :multiple => true, :size => Job.count } %>
  </div>
  <%= f.button "Save" %>
<% end %>

app/views/stacks/_index.html.erb
<div id="stacks" class="span11" style="margin-left:0px;">
  <% if params[:html] %>
    <div class="right">
      <%= link_to 'jobs', jobs_path %> &middot; 
      <%= link_to 'new stack', new_stack_path %>
    </div>
    <%= page_header("Stacks") %>
    <div class="row">
      <ul class="unstyled">
        <% @stacks.each do |stack| %>
          <li class="span5">
            <h2><%= link_to stack.display_name, stack %></h2>
            <%= render stack %>
          </li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <% content_for :javascript do %>
      <script type="text/javascript">
        window.router = new Capitan.Routers.StacksRouter({stacks: <%= raw @stacks.to_json %>});
        Backbone.history.start();
      </script>
    <% end %>
  <% end %>
</div>

app/views/stacks/_stack.html.erb
<div class='job_statuses'>
  <table class="table table-striped table-bordered table-condensed">
    <tbody>
      <tr>
        <td class="status <%= stack.display_result %>"><strong>Status</strong>: <%= stack.result_description %></td>
      </tr>
      <%- stack.jobs.each do |job| -%>
        <tr>
          <td class="status <%= job.display_result %>"><%= link_to job.display_name, job %></td>
        </tr>
      <%- end -%>
    </tbody>
  </table>
</div>

app/views/stacks/index.html.erb
<%= render "index" %>

app/views/stacks/new.html.erb
<%= render 'form' %>

app/views/stacks/show.html.erb
<div id="<%= dom_id(@stack) %>">
  <%= page_header("Stack - #{@stack.name}") %>
  <%= render @stack %>
  <%= render 'form' %>
</div>